[workspace]
members = ["backend", "shared", "cli"]
resolver = "3"

[workspace.dependencies]
libsql = "0.9.14"
serde = { version = "1.0.219", features = ["derive"] }
tokio = "1.46.1"
walkdir = "2.5.0"
