[package]
name = "cli"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.41", features = ["derive"] }
libsql = {workspace = true}
tokio = {workspace = true} 
walkdir = {workspace = true}
serde = { workspace = true }
dotenvy = "0.15.7"
